_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
agent_model:
    value: gpt-4o-mini
center_threshold:
    value: 10
device:
    value: auto
disable_completion_preface:
    value: false
disable_wandb:
    value: false
early_stop_max_years:
    value: 0
entity:
    value: null
exploiter_model:
    value: gpt-4o-mini
exploiter_powers:
    value: ""
exploiter_prompt:
    value: ""
fourbit_compute_dtype:
    value: 32
local_llm_path:
    value: null
log_level:
    value: INFO
manual_orders_path:
    value: null
map_name:
    value: standard_welfare
max_completion_errors:
    value: 30
max_message_rounds:
    value: 3
max_years:
    value: 10
no_press:
    value: false
no_press_policy:
    value: 0
no_press_powers:
    value: ""
output_folder:
    value: games
project:
    value: temporary
quantization:
    value: null
run_name:
    value: null
save:
    value: true
seed:
    value: 0
summarizer_model:
    value: gpt-4o-mini
super_exploiter_powers:
    value: ""
temperature:
    value: 1
top_p:
    value: 0.9
unit_threshold:
    value: 10
